version: '3.9'
services:
    spring-boot-crud-codebase-ms:
        container_name: spring-boot-crud-codebase-ms
        build:
            context: ./
            dockerfile: Dockerfile
        image: spring-boot-crud-codebase-ms:latest
        ports:
            - 8080:8080
        networks:
            - spring-boot-crud-codebase-network
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                limits:
                    cpus: '0.25'
                    memory: 250M
                reservations:
                    cpus: '0.1'
                    memory: 30M
        environment:
            - "environment=dev"
networks:
    spring-boot-crud-codebase-network:
        driver: bridge
        #driver: overlay